name: "Test"

on: [push, pull_request]

jobs:
  tests:
    name: "Code QA"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker images
        run: make build
      - name: Codestyle check
        run: make phpcs
      - name: Static analysis
        run: make phpstan
      - name: Tests
        run: make tests

