name: "Test"

on: [push, pull_request]

jobs:
  tests:
    name: "Code QA"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker images
        run: make build
      - name: Codestyle check
        run: make phpcs ALLOWED_VOLUME=0
      - name: Static analysis
        run: make phpstan ALLOWED_VOLUME=0
      - name: Tests
        run: make tests ALLOWED_VOLUME=0

